'use strict';
const $=s=>document.querySelector(s), app=$('#app'), dialog=$('#dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={token:sessionStorage.getItem('anhs-session')||'',teacher:null,ref:null,data:null,cacheKey:'',route:{page:'home'},selected:new Set(),entryType:'incident',requestID:'',pinToken:'',remember:true};
const uuid=()=>crypto.randomUUID();
const btn=(label,act,value='',cls='')=>`<button type="button" class="${cls}" data-act="${esc(act)}" data-value="${esc(value)}">${esc(label)}</button>`;
const opt=(v,label,chosen)=>`<option value="${esc(v)}" ${String(chosen)===String(v)?'selected':''}>${esc(label??v)}</option>`;
const manager=()=>['Head of Grade','HOD','Admin'].includes(S.teacher?.role);
const allAccess=()=>['HOD','Admin'].includes(S.teacher?.role);
const canManage=l=>manager()&&(S.teacher.role!=='Head of Grade'||String(l?.grade)===String(S.teacher.headOfGrade));
const today=()=>S.ref?.today||new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nice=d=>d?String(d).slice(0,10):'—';
function notify(s){$('#notice').textContent=s;$('#notice').style.display='block';clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').style.display='none',7000);}
const overviewCache=new Map(),overviewPending=new Map();let dataEpoch=0,routeEpoch=0,activeRequests=0,sessionEpoch=0,modalEpoch=0;
const stale=()=>Object.assign(Error("Superseded request"),{stale:true});
function ticket(){return {nav:routeEpoch,session:sessionEpoch};}
function current(t){return t.nav===routeEpoch&&t.session===sessionEpoch;}
function assertCurrent(t){if(!current(t))throw stale();}
function loadingNote(note){return `<div class="loading-note" role="status"><img src="anhs-crest.png" alt="ANHS crest" width="56" height="56"><span class="spinner" aria-hidden="true"></span><p>${esc(note)}</p></div>`;}
function startup(note){const el=$("#startup-loader");if(el){el.innerHTML=loadingNote(note);el.hidden=false;}}
function endStartup(){const el=$("#startup-loader");if(el)el.hidden=true;}
function requestStatus(){const el=$('#request-status');if(el){el.hidden=!activeRequests;el.textContent=activeRequests?'Loading… please wait.':'';}}
function invalidateViews(){dataEpoch++;overviewCache.clear();overviewPending.clear();S.cacheKey='';}
async function api(action,data={},token=S.token){
 activeRequests++;requestStatus();const start=performance.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{
  const res=await fetch(ANHS_CONFIG.api,{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,data:{...data,sessionToken:token}}),cache:'no-store',signal:controller.signal});
  const body=await res.json();S.timing={action,roundTrip:Math.round(performance.now()-start),upstream:res.headers.get('X-JBP-Upstream-Ms'),attempts:res.headers.get('X-JBP-Upstream-Attempts'),bridge:body.bridge||{},backend:body.performance?.totalMs,stages:body.performance?.stages||{}};
  if(body.result?.summaryWarning)notify(body.result.summaryWarning);if(!body.ok)throw Object.assign(Error(body.error||'Request failed.'),{code:body.code,status:res.status});return body.result;
 }catch(e){if(e.name==='AbortError')throw Error('Request reached the 30-second limit. If saving, check the record before trying again.');throw e;}finally{clearTimeout(timer);activeRequests--;requestStatus();}
}
function panel(title,body){S.loading=body.includes('class="loading-note"');app.innerHTML=`<section class="panel"><div class="no-print navigation">${S.teacher?btn('‹ Back','back','','link')+btn('Refresh','refresh','','link'):''}</div><div class="report-title"><strong>Aliwal North High School</strong><p>ANHS Discipline App · ${esc(ANHS_CONFIG.version)} · ${esc(today())}</p></div><h1>${esc(title)}</h1>${body}</section>`;}
function go(route,replace=false){window.scrollTo?.(0,0);routeEpoch++;S.route=route;if(replace)history.replaceState(route,'','#'+route.page);else history.pushState(route,'','#'+route.page);const t=ticket();render().catch(e=>{if(current(t))showError(e);});}
function showError(e){if(e.stale)return;if(S.loading)panel('Unable to load this view',`<p>${esc(e.message||String(e))}</p><p>Use Refresh to try again, or choose Home or Back.</p>`);notify(e.message||String(e));if(/session has expired|sign in again|no longer active/i.test(e.message)){S.token='';sessionStorage.removeItem('anhs-session');login();}}
window.addEventListener('popstate',e=>{routeEpoch++;S.route=e.state||{page:'home'};const t=ticket();render().catch(e=>{if(current(t))showError(e);});});
$('#home').onclick=()=>go({page:'home'});
function login(){S.loading=false;sessionEpoch++;endStartup();invalidateViews();routeEpoch++;S.teacher=null;S.data=null;S.ref=null;S.savedReceipt=null;S.draft=null;S.requestID='';$('#home').hidden=true;app.innerHTML=`<section class="panel login"><img class="login-logo" src="anhs-crest.png" alt="ANHS crest"><h1>ANHS Discipline App</h1><p style="text-align:center">Ons Trop, Ons Trots</p><form id="login-form"><label>Username<input name="username" autocomplete="username" required></label><label>PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="current-password" required></label><label class="check"><input name="remember" type="checkbox" checked>Remember this device</label><div class="form-error"></div><button class="full">Sign in</button></form><hr><button id="install" type="button" class="secondary full" data-act="install">Install for Android</button><p><strong>Using an iPhone?</strong><br>Open this app in Safari, tap Share, then Add to Home Screen.</p><div class="bottom">${btn('About','about','','link')}</div></section>`;}
function pinForm(){panel('Choose your own PIN',`<p>Enter a new four-digit PIN, different from your temporary PIN.</p><form id="pin-form"><label>New PIN<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="new-password" required></label><label>Confirm PIN<input name="confirm" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" autocomplete="new-password" required></label><div class="form-error"></div><button>Save PIN</button></form>`);}
function checkVersion(ref){if(ref.version&&ref.version!==ANHS_CONFIG.version)throw Error('App and backend versions differ. Deploy the v0.97b backend and refresh the app.');}
async function acceptLogin(r,t=ticket()){assertCurrent(t);if(r.mustChangePIN){S.pinToken=r.pinChangeToken;pinForm();return;}if(!r.sessionToken)throw Error('Please sign in again.');const ref=r.appData||await api('getAppData',{},r.sessionToken);assertCurrent(t);checkVersion(ref);S.token=r.sessionToken;sessionStorage.setItem('anhs-session',S.token);if(r.rememberToken)localStorage.setItem('anhs-remember',r.rememberToken);S.ref=ref;S.teacher=ref.teacher;invalidateViews();$('#home').hidden=false;go({page:'home'},true);}

function home(){const t=S.teacher;const menu=[btn('Teacher Dashboard','teacher')];if(manager())menu.push(btn('Head of Grade Dashboard','grade'));if(allAccess())menu.push(btn('HOD Dashboard','hod'));menu.push(btn('Record Incident','record','incident'),btn('Record Observation','record','observation'));if(t.role==='Admin')menu.push(btn('Manage Users','users'),btn('System Diagnostics','diagnostics'));panel('Welcome, '+t.name,`<p class="eyebrow">${esc(t.role)}${t.registerClass?' · Register '+esc(t.registerClass):''}${t.headOfGrade?' · Grade '+esc(t.headOfGrade):''}</p><div class="grid menu">${menu.join('')}</div><div class="bottom">${btn('Sign out','logout','','danger')}${btn('About','about','','secondary')}</div>`);prefetchDashboard();}
function overviewArgs(route){return {scope:route.scope||'teacher',grade:route.grade||'',learnerID:route.learnerID||'',history:['all','learner'].includes(route.page)?'full':'current',offset:route.offset||0};}
async function fetchOverview(route){
 const epoch=dataEpoch,session=sessionEpoch,args=overviewArgs(route),key=JSON.stringify(args);
 const item=overviewCache.get(key);if(item&&Date.now()-item.at<30000)return item.data;
 let pending=overviewPending.get(key);
 if(!pending){const force=Boolean(S.forceOverview);S.forceOverview=false;pending=api('overview',{...args,force}).then(data=>{if(epoch!==dataEpoch||session!==sessionEpoch)throw stale();overviewCache.set(key,{data,at:Date.now()});if(overviewCache.size>8)overviewCache.delete(overviewCache.keys().next().value);return data;}).finally(()=>{if(overviewPending.get(key)===pending)overviewPending.delete(key);});overviewPending.set(key,pending);}
 if(item){const t=ticket();pending.then(()=>{if(current(t)&&S.cacheKey===key&&['dashboard','recent','unresolved','risk'].includes(S.route.page)){render().catch(e=>{if(current(t))showError(e);});}}).catch(e=>{if(!e.stale&&current(t)&&S.cacheKey===key)notify('Showing previously loaded records. '+e.message);});return item.data;}
 return pending;
}
async function loadOverview(route,t=ticket()){
 let data;try{data=await fetchOverview(route);}catch(e){if(!e.stale||!current(t))throw e;data=await fetchOverview(route);}assertCurrent(t);S.data=data;S.cacheKey=JSON.stringify(overviewArgs(route));return data;
}
function prefetchDashboard(){if(!S.teacher)return;const t=S.teacher;const route=t.role==='Head of Grade'&&t.headOfGrade?{scope:'grade',grade:t.headOfGrade}:allAccess()?{scope:'all'}:{scope:t.registerClass?'register':'teacher'};fetchOverview(route).catch(()=>{});}
const dashboardButtons=[['Recent Incidents','recent'],['Unresolved Incidents','unresolved'],['High Risk Learners','risk'],['Learner History','learners'],['Class History','classes'],['All Incidents','all'],['Discipline Trends','trends'],['Reports/Exports','reports']];
function dashboardLoading(route,label){const menu=route.scope==='teacher'?`${S.teacher.registerClass?btn('My Register Class '+S.teacher.registerClass,'register'):''}${btn('View My History','my-history','','secondary')}`:dashboardButtons.map(([a,b])=>btn(a,'view',b)).join('');panel(label,`${route.scope==='all'?`<label>Select Grade<select id="grade-filter">${opt('','All grades',route.grade)}${[8,9,10,11,12].map(n=>opt(n,'Grade '+n,route.grade)).join('')}</select></label>`:''}${loadingNote('Loading dashboard totals and recent incidents…')}<div class="grid menu">${menu}</div>`);}

function stats(d){return `<div class="stats"><div class="stat"><strong>${d.summary.unresolved}</strong><small>Unresolved items</small></div><div class="stat"><strong>${d.summary.recent}</strong><small>Incidents · last 7 days</small></div><div class="stat common"><strong>${esc(d.summary.common)}</strong><small>Most common · last 7 days</small></div><div class="stat"><strong>${d.summary.highRisk}</strong><small>High Risk Learners</small></div></div>`;}
function learnerFor(id){return S.data?.learners.find(l=>l.id===id)||S.ref.learners.find(l=>l.id===id);}
function interventionPrompt(l){return (l?.interventions||[]).filter(i=>i.Status==='Open'&&String(i.Year)===today().slice(0,4)).map(i=>`<div class="prompt"><strong>${i.Threshold} points · ${esc(i.Action)}</strong><br><small>Open intervention</small>${canManage(l)?`<div class="actions">${btn('Resolve intervention','resolve','intervention:'+i.ID)}</div>`:''}</div>`).join('');}
function incidentCard(r,withPrompt=true){const l=learnerFor(r.LearnerID),can=canManage(l);return `<article class="card ${r.RemovedAt?'removed':''}"><div class="row between"><h3>${esc(r.LearnerName)}</h3><span class="badge">${esc(l?.className||r.Class)}</span></div><strong>${esc(r.Code)} · ${esc(r.Offence)}</strong><p>${esc(r.Details)}</p><span class="badge ${r.ApprovalStatus==='Pending'?'warn':''}">${r.ApprovalStatus==='Pending'?'Awaiting approval':esc(r.Points)+' pts'}</span>${r.RemovedAt?'<span class="badge red">Removed</span>':`<span class="badge">${esc(r.ApprovalStatus==='Rejected'?'Rejected':r.ReviewStatus)}</span>`}${l?.points!=null?`<span class="badge">Total points: ${l.points}</span>`:''}<p><small>Recorded by ${esc(r.RecordedName)} · Occurred ${nice(r.DateOccurred)} · ${esc(r.Period)}</small></p>${r.ReviewComment||r.ResolutionAction?`<p class="subtle">${esc(r.ResolutionAction)}<br>${esc(r.ReviewComment)}<br><small>${esc(r.ReviewedBy)} · ${nice(r.ReviewedAt)}</small></p>`:''}${r.RemovedAt?`<p class="subtle">${esc(r.RemovalReason)} ${esc(r.RemovalDetails)}<br><small>Removed by ${esc(r.RemovedBy)} · ${nice(r.RemovedAt)}</small></p>`:''}${can&&!r.RemovedAt?`<div class="actions">${r.ApprovalStatus==='Pending'?btn('Approve / reject','approval',r.ID):r.ApprovalStatus==='Approved'&&r.ReviewStatus==='Open'?btn('Resolve incident','resolve','incident:'+r.ID):''}${btn('Remove incident','remove',r.ID,'danger')}</div>`:''}${withPrompt?interventionPrompt(l):''}</article>`;}
function observationCard(r){const l=learnerFor(r.LearnerID);return `<article class="card"><h3>${esc(r.LearnerName)} · Observation</h3><span class="badge">${esc(r.Type)}</span><span class="badge">No points</span>${r.NeedsAttention==='Yes'?`<span class="badge warn">${esc(r.Status)} · Head of Grade attention</span>`:''}<p>${esc(r.Details)}</p><small>${nice(r.DateOccurred)} · ${esc(r.Period)} · ${esc(r.RecordedName)}</small>${r.Comment||r.ResolutionAction?`<p>${esc(r.ResolutionAction)}<br>${esc(r.Comment)}<br><small>${esc(r.ResolvedBy)} · ${nice(r.ResolvedAt)}</small></p>`:''}${r.Status==='Open'&&canManage(l)?`<div class="actions">${btn('Resolve observation','resolve','observation:'+r.ID)}</div>`:''}</article>`;}
function interventionCard(i){const l=learnerFor(i.LearnerID);return `<article class="card"><h3>${esc(l?l.surname+', '+l.name:i.LearnerID)}</h3><strong>${esc(i.Action)}</strong><p><span class="badge">${i.Threshold} points</span><span class="badge ${i.Status==='Open'?'warn':'green'}">${esc(i.Status)}</span></p>${i.Comment||i.ResolutionAction?`<p>${esc(i.ResolutionAction)}<br>${esc(i.Comment)}<br><small>${esc(i.ResolvedBy)} · ${nice(i.ResolvedAt)}</small></p>`:''}${i.Status==='Open'&&canManage(l)?btn('Resolve intervention','resolve','intervention:'+i.ID):''}</article>`;}
function empty(s='No records to display.'){return `<p class="empty">${esc(s)}</p>`;}
function recentInc(d){const cutoff=offsetDate(d.today,-6);return d.incidents.filter(r=>!r.RemovedAt&&r.ApprovalStatus!=='Rejected'&&r.DateOccurred>=cutoff&&r.DateOccurred<=d.today);}
function offsetDate(s,days){return new Date(new Date(s+'T12:00:00Z').getTime()+days*86400000).toISOString().slice(0,10);}
async function dashboard(route){const t=ticket();const label=route.scope==='all'?'HOD Dashboard':route.scope==='grade'?'Head of Grade Dashboard':route.scope==='register'?'My Register Class '+S.teacher.registerClass:'Teacher Dashboard';dashboardLoading(route,label);const d=await loadOverview(route.scope==='teacher'&&S.teacher.registerClass?{...route,scope:'register'}:route,t);assertCurrent(t);
 let top='';if(route.scope==='all')top=`<label class="no-print">Select Grade<select id="grade-filter">${opt('','All grades',route.grade)}${[8,9,10,11,12].map(n=>opt(n,'Grade '+n,route.grade)).join('')}</select></label>`;
 if(route.scope==='teacher'){panel(label,`<p>${esc(S.teacher.name)}</p>${S.teacher.registerClass?btn('My Register Class '+S.teacher.registerClass,'register')+stats(d):''}<h2>${S.teacher.registerClass?'Register class recent incidents':'My recent entries'} (${recentInc(d).length})</h2><p class="muted">${S.teacher.registerClass?'Incidents for my register class':'Entries I recorded'} in the last 7 days</p>${btn('View My History','my-history','','secondary')}<div style="margin-top:18px">${recentInc(d).map(r=>incidentCard(r)).join('')||empty()}</div>`);return;}
 const buttons=[['Recent Incidents','recent'],['Unresolved Incidents','unresolved'],['High Risk Learners','risk'],['Learner History','learners'],['Class History','classes'],['All Incidents','all'],['Discipline Trends','trends'],['Reports/Exports','reports']];
 panel(label,`${top}${route.scope==='grade'?`<p class="eyebrow">Grade ${esc(route.grade||S.teacher.headOfGrade)}</p>`:''}${stats(d)}<div class="grid menu no-print">${buttons.map(([a,b])=>btn(a,'view',b)).join('')}</div>${route.scope==='register'?`<h2>Recent Incidents</h2>${recentInc(d).map(r=>incidentCard(r)).join('')||empty()}`:''}`);
}
function viewRoute(page){go({...S.route,page});}
function historyTable(ls){return `<div class="scroll"><table><thead><tr><th>Learner</th><th>Points</th></tr></thead><tbody>${ls.sort((a,b)=>(a.surname+a.name).localeCompare(b.surname+b.name)).map(l=>`<tr><td>${btn(l.surname+', '+l.name,'learner',l.id,'link')}${!l.active?' (inactive)':''}</td><td>${l.points??'—'}</td></tr>`).join('')}</tbody></table></div>`;}
async function listPage(route){const t=ticket();panel(({recent:'Recent Incidents',all:'Incident History',unresolved:'Unresolved Incidents',risk:'High Risk Learners',learners:'Learner History',classes:'Class History',learner:'Learner History'})[route.page],loadingNote('Loading records…'));const d=await loadOverview(route,t);assertCurrent(t);let body='',title='';const exportButton=`<div class="actions no-print">${btn('Save to PDF / Print','print','','secondary')}</div>`;
 if(route.page==='recent'){title='Recent Incidents · last 7 days';body=`<p class="muted">Offence dates ${esc(offsetDate(d.today,-6))} to ${esc(d.today)}. ${esc(d.viewInfo?.scope==='register'?'Register class '+(d.viewInfo.registerClass||''):d.viewInfo?.scope==='teacher'?'Entries recorded by you':d.viewInfo?.scope==='grade'?'Selected grade':'Selected permitted learners')}.</p>`+(recentInc(d).map(r=>incidentCard(r)).join('')||empty('No matching incidents in this seven-day offence-date window. Check All Incidents for older entries. Admin can check System Diagnostics for unmatched accession numbers or invalid dates.'));}
 if(route.page==='all'){title=route.scope==='teacher'?'My Entry History':'All Incidents';body=d.incidents.map(r=>incidentCard(r)).join('')||empty();if(route.scope==='teacher')body+='<h2>My observations</h2>'+(d.observations.map(observationCard).join('')||empty());}
 if(route.page==='unresolved'){title='Unresolved Incidents';const year=today().slice(0,4);body='<p class="muted">Incidents, interventions and flagged observations awaiting action.</p>'+d.interventions.filter(i=>i.Status==='Open'&&String(i.Year)===year).map(interventionCard).join('')+d.incidents.filter(r=>!r.RemovedAt&&r.ReviewStatus==='Open'&&String(r.DateOccurred).startsWith(year)).map(r=>incidentCard(r,false)).join('')+d.observations.filter(r=>r.Status==='Open'&&String(r.DateOccurred).startsWith(year)).map(observationCard).join('');}
 if(route.page==='risk'){title='High Risk Learners';const ls=d.learners.filter(l=>l.active&&l.highRisk).sort((a,b)=>b.points-a.points);body='<p class="muted">40 or more current-year points and an offence within the past three months.</p>'+ls.map(l=>`<article class="card"><h3>${btn(l.surname+', '+l.name,'learner',l.id,'link')}</h3><span class="badge red">${l.points} points</span><span class="badge">${esc(l.className)}</span><small>Latest offence: ${nice(l.lastOffence)}</small>${interventionPrompt(l)}</article>`).join('');if(!ls.length)body+=empty();}
 if(route.page==='learners'){title='Learner History';body=`<label>Search learner<input id="history-search" placeholder="Surname, name or accession number"></label><div id="history-results">${historyTable(d.learners)}</div>`;}
 if(route.page==='classes'){title='Class History';const classes=[...new Set(d.learners.map(l=>l.className))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));const c=route.className||classes[0]||'';body=`<label class="no-print">Class<select id="class-history">${classes.map(x=>opt(x,x,c)).join('')}</select></label><h2>${esc(c)} · current-year points</h2>${historyTable(d.learners.filter(l=>l.className===c))}${exportButton}`;}
 if(route.page==='learner'){const l=d.learners[0];title=l.surname+', '+l.name;body=`<p>${esc(l.className)} · Accession Number ${esc(l.id)}</p><span class="badge">${l.points} current-year points</span>${l.highRisk?'<span class="badge red">High Risk</span>':''}<h2>Intervention history</h2>${d.interventions.map(interventionCard).join('')||empty()}<h2>Incidents</h2>${d.incidents.map(r=>incidentCard(r,false)).join('')||empty()}<h2>Observations</h2>${d.observations.map(observationCard).join('')||empty()}${exportButton}`;}
 panel(title,body+(['all','learner','recent','unresolved'].includes(route.page)&&d.page?.hasMore?`<div class="actions">${btn('Load more records','more')}</div>`:''));
}
function picker(){const ref=S.ref;panel(S.entryType==='incident'?'Record Incident':'Record Observation',`<label>Find a learner<input id="learner-search" placeholder="Surname, name or accession number"></label><label class="check"><input id="multi" type="checkbox">Select multiple learners for the same ${S.entryType}</label><div id="class-picker">${classGrid(ref.classes)}</div><div class="learner-list" id="learner-results"></div><div id="selection-bar"></div>`);}
function classGrid(classes){return `<div class="class-grid">${[8,9,10,11,12].map(g=>{const a=classes.filter(c=>parseInt(c,10)===g);if(!a.length)return '';return a.map(c=>btn(c,'class',c)).join('')+Array(Math.max(0,4-a.length)).fill('<span aria-hidden="true"></span>').join('');}).join('')}</div>`;}
function chooseLearners(ls){$('#learner-results').innerHTML=ls.sort((a,b)=>(a.surname+a.name).localeCompare(b.surname+b.name)).map((l,n)=>btn((S.selected.has(l.id)?'✓ ':'')+(n+1)+'. '+l.surname+', '+l.name+' · '+l.className,'choose',l.id)).join('')||empty('No matching learners.');$('#selection-bar').innerHTML=S.selected.size?btn('Continue ('+S.selected.size+')','entry') : '';}
function entryForm(){const labels=[...S.selected].map(id=>S.ref.learners.find(l=>l.id===id)).filter(Boolean).map(l=>l.surname+', '+l.name).join('; ');const incident=S.entryType==='incident';S.requestID=S.requestID||uuid();panel(incident?'Incident details':'Observation details',`<p class="subtle">${esc(labels)}</p><form id="entry-form">${incident?`<h2>Select offence</h2><div class="grid quick">${['1-07','1-02','1-01','1-11'].map(c=>{const o=S.ref.offences.find(o=>o.Code===c);return o?btn(o.QuickLabel+' · '+o.Points+' pts','quick',c):'';}).join('')}</div>${btn('Other — full offence list','other','','secondary full')}<label id="offence-label">Offence<select name="code" id="offence" required><option value="">Choose an offence</option>${S.ref.offences.map(o=>opt(o.Code,o.Code+' · '+o.Description+' ('+(Number(o.MinPoints)===Number(o.MaxPoints)?o.Points:o.MinPoints+'–'+o.MaxPoints)+' pts)')).join('')}</select></label><div id="approval-note"></div>`:`<label>Observation type<select name="type">${['Warning Issued','Parent Contact','General Behaviour','Other'].map(x=>opt(x)).join('')}</select></label><label class="check"><input name="attention" type="checkbox">Needs Head of Grade attention</label><p class="muted">Observations carry no points.</p>`}<div class="grid"><label>Offence / observation date<input name="date" type="date" value="${today()}" max="${today()}" required></label><label>Period<select name="period" required><option value="">Choose period</option>${S.ref.periods.map(x=>opt(x)).join('')}</select></label></div><label>Details <small>(required)</small><textarea name="details" required maxlength="4000"></textarea></label><div class="form-error"></div><button>Submit ${incident?'incident':'observation'}</button></form>`);restoreDraft();}
function offenceChanged(){const o=S.ref.offences.find(x=>x.Code===$('#offence').value);$('#approval-note').innerHTML=!o?'':`${o.Approval==='Yes'?`<p class="prompt">Approval required. No points count until a Head of Grade, HOD or Admin approves.</p>${Number(o.MinPoints)!==Number(o.MaxPoints)?`<label>Recommended points (optional)<input name="recommended" type="number" min="${o.MinPoints}" max="${o.MaxPoints}" step="1"></label>`:''}`:''}${o.Restricted==='Yes'?'<label class="check"><input name="confirmedTest" type="checkbox" required>I confirm the school has a confirmed test result.</label>':''}`;}
function modal(title,html){modalEpoch++;dialog.innerHTML=`<h2>${esc(title)}</h2>${html}<div class="actions">${btn('Close','close','','secondary')}</div>`;dialog.showModal();}
function actionModal(kind,id,action){const source=kind==='incident'?S.data.incidents:kind==='observation'?S.data.observations:S.data.interventions;const r=source.find(r=>r.ID===id);if(!r)return;let html='';if(action==='remove')html=`<label>Reason<select name="reason" required><option value="">Select reason</option>${S.ref.removalReasons.map(x=>opt(x)).join('')}</select></label><label>Details (required for Other)<textarea name="comment"></textarea></label>`;else if(action==='approval'){const o=S.ref.offences.find(o=>o.Code===r.Code);html=`<p>${esc(r.Offence)}</p>${r.RecommendedPoints!==''?`<p>Teacher recommendation: ${esc(r.RecommendedPoints)} points</p>`:''}<label>Decision<select name="decision"><option value="approve">Approve</option><option value="reject">Reject</option></select></label>${o?`<label>Final points<input type="number" name="points" min="${o.MinPoints}" max="${o.MaxPoints}" step="1" value="${Number(o.MinPoints)===Number(o.MaxPoints)?o.Points:r.RecommendedPoints||o.MinPoints}" ${Number(o.MinPoints)===Number(o.MaxPoints)?'readonly':''}></label>`:''}<label>Comment / rejection reason<textarea name="comment"></textarea></label>`;}else html=`<label>Action taken<select name="resolutionAction" required><option value="">Select an action</option>${S.ref.resolveActions.map(x=>opt(x)).join('')}</select></label><label>Comment ${kind==='incident'?'(optional)':'(required)'}<textarea name="comment" ${kind==='incident'?'':'required'} maxlength="4000"></textarea></label>`;modal(action==='remove'?'Remove incident':action==='approval'?'Approve or reject':'Resolve item',`<form id="action-form" data-kind="${kind}" data-id="${esc(id)}" data-action="${action}">${html}<div class="form-error"></div><button>Save decision</button></form>`);}
function rangeFilter(d){return `<div class="grid no-print"><label>Period<select id="range">${[['7','Last 7 days'],['30','Last 30 days'],['term','This term'],['year','This year'],['custom','Custom dates']].map(([v,l])=>opt(v,l,'7')).join('')}</select></label><div class="grid"><label>From<input type="date" id="from" value="${offsetDate(d.today,-6)}"></label><label>To<input type="date" id="to" value="${d.today}"></label></div></div>`;}
function filteredRecords(){const a=$('#from').value,b=$('#to').value;if(!a||!b||a>b)throw Error('Choose a valid date range.');return S.data.incidents.filter(r=>!r.RemovedAt&&r.ApprovalStatus==='Approved'&&r.DateOccurred>=a&&r.DateOccurred<=b);}
function bars(counts){const a=Object.entries(counts).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...a.map(x=>x[1]));return a.map(([k,n])=>`<div class="bar-row"><span>${esc(k)}</span><div><div class="bar" style="width:${n/max*100}%"></div></div><strong>${n}</strong></div>`).join('')||empty();}
let trendEpoch=0;
async function drawTrends(){const t=ticket(),generation=++trendEpoch,from=$('#from').value,to=$('#to').value;try{if(!from||!to||from>to)throw Error('Choose a valid date range.');const d=await api('trendData',{...overviewArgs(S.route),from,to});if(!current(t)||generation!==trendEpoch)return;$('#trend-output').innerHTML=`<p>${esc(from)} to ${esc(to)} · ${d.total} approved incidents</p><h2>Most common offences</h2>${bars(Object.fromEntries(d.offences.map(r=>[r.Offence,r.Count])))}<h2>Incidents per week</h2>${bars(Object.fromEntries(d.weeks.map(r=>['Week of '+r.Week,r.Count])))}`;}catch(e){if(current(t)&&generation===trendEpoch)notify(e.message);}}
async function trends(route){const t=ticket();panel('Discipline Trends',loadingNote('Loading history…'));const d=await loadOverview(route,t);assertCurrent(t);panel('Discipline Trends',`${rangeFilter(d)}<div class="no-print actions">${btn('Save to PDF / Print','print','','secondary')}</div><div id="trend-output"></div>`);drawTrends();}
async function reports(route){const t=ticket();panel('Reports / Exports',loadingNote('Loading history…'));const d=await loadOverview(route,t);assertCurrent(t);panel('Reports / Exports',`<div class="no-print"><label>Report<select id="report-type">${[['learner','Learner history'],['class','Class points list'],['unresolved','Unresolved incidents and interventions'],['risk','High Risk Learners'],['offences','Incident summary by offence']].map(([v,l])=>opt(v,l)).join('')}</select></label><label>Class<select id="report-class">${opt('','All permitted classes')}${[...new Set(d.learners.map(l=>l.className))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(c=>opt(c)).join('')}</select></label><label>Learner (for learner history)<select id="report-learner">${d.learners.map(l=>opt(l.id,l.surname+', '+l.name+' · '+l.className)).join('')}</select></label></div>${rangeFilter(d)}<div class="actions no-print">${btn('Generate report','generate')}${btn('Save to PDF / Print','print','','secondary')}</div><div id="report-output"></div>`);}
let reportEpoch=0;
async function generateReport(){const t=ticket(),generation=++reportEpoch;try{const args={...overviewArgs(S.route),from:$('#from').value,to:$('#to').value,className:$('#report-class').value};if(!args.from||!args.to||args.from>args.to)throw Error('Choose a valid date range.');const snapshot=await api('reportData',args);if(!current(t)||generation!==reportEpoch)return;S.data=snapshot;const type=$('#report-type').value,cls=$('#report-class').value,a=filteredRecords().filter(r=>!cls||learnerFor(r.LearnerID)?.className===cls),d=S.data,from=$('#from').value,to=$('#to').value;let body='';if(type==='learner'){const id=$('#report-learner').value,l=learnerFor(id);if(!l)throw Error('Choose a learner.');body=`<h2>${esc(l.surname+', '+l.name)}</h2><p>${esc(l.className)} · Current-year points: ${l.points}</p><h3>Incidents</h3>${d.incidents.filter(r=>r.LearnerID===id&&r.DateOccurred>=from&&r.DateOccurred<=to).map(r=>incidentCard(r,false)).join('')||empty()}<h3>Observations</h3>${d.observations.filter(r=>r.LearnerID===id&&r.DateOccurred>=from&&r.DateOccurred<=to).map(observationCard).join('')||empty()}<h3>Interventions created in selected period</h3>${d.interventions.filter(r=>r.LearnerID===id&&nice(r.CreatedAt)>=from&&nice(r.CreatedAt)<=to).map(interventionCard).join('')||empty()}`;}
 if(type==='class'){body='<h2>Class points list</h2><p>Points from approved offences in the selected date range.</p>'+historyTable(d.learners.filter(l=>!cls||l.className===cls).map(l=>({...l,points:a.filter(r=>r.LearnerID===l.id).reduce((n,r)=>n+Number(r.Points),0)})));}
 if(type==='offences'){const c={};a.forEach(r=>{const k=r.Code+' · '+r.Offence;if(!c[k])c[k]={count:0,points:0};c[k].count++;c[k].points+=Number(r.Points);});body='<h2>Incident summary by offence</h2><table><tr><th>Offence</th><th>Incidents</th><th>Points</th></tr>'+Object.entries(c).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${v.count}</td><td>${v.points}</td></tr>`).join('')+'</table>';}
 if(type==='risk'){body='<h2>Current High Risk Learners</h2><p>Current-year rule; selected dates filter each learner’s latest offence.</p>'+historyTable(d.learners.filter(l=>l.active&&l.highRisk&&(!cls||l.className===cls)&&l.lastOffence>=from&&l.lastOffence<=to));}
 if(type==='unresolved'){const allowed=r=>(!cls||learnerFor(r.LearnerID)?.className===cls);body='<h2>Unresolved items</h2>'+d.incidents.filter(r=>allowed(r)&&!r.RemovedAt&&r.ReviewStatus==='Open'&&r.DateOccurred>=from&&r.DateOccurred<=to&&String(r.DateOccurred).startsWith(today().slice(0,4))).map(r=>incidentCard(r,false)).join('')+d.interventions.filter(r=>allowed(r)&&r.Status==='Open'&&String(r.Year)===today().slice(0,4)&&nice(r.CreatedAt)>=from&&nice(r.CreatedAt)<=to).map(interventionCard).join('')+d.observations.filter(r=>allowed(r)&&r.Status==='Open'&&r.DateOccurred>=from&&r.DateOccurred<=to&&String(r.DateOccurred).startsWith(today().slice(0,4))).map(observationCard).join('');}
 $('#report-output').innerHTML=`<hr><p>${esc(from)} to ${esc(to)}${cls?' · '+esc(cls):''}</p>${body}`;
 }catch(e){if(current(t)&&generation===reportEpoch)notify(e.message);}}
function changeRange(){const v=$('#range').value,d=S.data;let from=$('#from').value,to=d.today;if(v==='7'||v==='30')from=offsetDate(to,-Number(v)+1);if(v==='year')from=to.slice(0,4)+'-01-01';if(v==='term'){const terms=d.calendar.filter(t=>t.start&&t.end&&t.start<=to&&t.end>=to);if(terms.length!==1){notify('This term is unavailable. Enter valid term dates in TermCalendar.');return;}from=terms[0].start;to=terms[0].end;}if(v!=='custom'){$('#from').value=from;$('#to').value=to;}if(S.route.page==='trends')drawTrends();else if($('#report-output'))$('#report-output').innerHTML='';}
async function users(){const t=ticket();panel('Manage Users',loadingNote('Loading user list…'));const us=await api('getAdminUsers');assertCurrent(t);S.users=us;panel('Manage Users',`${btn('Add user','user-edit')}${btn('Learner / user CSV imports and exports','data-admin','','secondary')}<div class="scroll"><table><tr><th>Name</th><th>Role</th><th>Class / Grade</th><th>Status</th><th></th></tr>${S.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.role)}</td><td>${esc(u.registerClass||'—')} / ${esc(u.headOfGrade||'—')}</td><td>${esc(u.active)}</td><td>${btn('Edit','user-edit',u.teacherID,'secondary')}</td></tr>`).join('')}</table></div>`);}
function editUser(id){const u=S.users.find(u=>u.teacherID===id)||{};modal(id?'Edit user':'Add user',`<form id="user-form" data-id="${esc(id)}"><label>Name<input name="name" required value="${esc(u.name||'')}"></label><label>Username<input name="username" required value="${esc(u.email||'')}"></label><label>Temporary PIN ${id?'(leave blank to retain current PIN)':''}<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" ${id?'':'required'} autocomplete="new-password"></label><label>Role<select name="role">${['Teacher','Head of Grade','HOD','Admin'].map(x=>opt(x,x,u.role)).join('')}</select></label><label>Register class<select name="registerClass">${opt('','None',u.registerClass)}${S.ref.classes.map(x=>opt(x,x,u.registerClass)).join('')}</select></label><label>Head of Grade assignment<select name="headOfGrade">${opt('','None',u.headOfGrade)}${[8,9,10,11,12].map(x=>opt(x,'Grade '+x,u.headOfGrade)).join('')}</select></label><label class="check"><input name="active" type="checkbox" ${!id||u.active==='Yes'?'checked':''}>Active</label><p class="muted">A new temporary PIN requires a change at the next sign-in.</p><div class="form-error"></div><button>Save user</button></form>`);}
async function diagnostics(){const previous=S.timing,t=ticket();panel('System Diagnostics',loadingNote('Checking database…'));const d=await api('getSystemDiagnostics'),timing=S.timing;assertCurrent(t);panel('System Diagnostics',`<p class="prompt">${d.passed?'Database checks passed.':'Database checks need attention.'}</p><div class="stats"><div class="stat"><strong>${timing.roundTrip} ms</strong><small>Total round trip</small></div><div class="stat"><strong>${timing.backend} ms</strong><small>Worker and D1</small></div></div><p>Storage: Cloudflare D1 · ${esc(d.version)}</p><h2>Previous request</h2><p>${esc(previous?.action||'None')} · ${previous?.roundTrip??'—'} ms total · ${previous?.backend??'—'} ms backend</p><h2>Request timings</h2><table>${Object.entries(timing.stages).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${v} ms</td></tr>`).join('')}</table><h2>Database tables</h2><table><tr><th>Table</th><th>Rows</th></tr>${d.sheets.map(x=>`<tr><td>${esc(x.name)}</td><td>${x.rows}</td></tr>`).join('')}</table><p>${esc(d.caches)}</p>${d.warnings.length?'<h2>Data checks</h2><ul>'+d.warnings.map(w=>'<li>'+esc(w)+'</li>').join('')+'</ul>':''}<p>Checked ${esc(d.checkedAt)}</p><div class="actions">${btn('Run again','diagnostics')}${btn('Imports and exports','data-admin','','secondary')}</div>`);}
function about(){modal('About ANHS Discipline App',`<p><strong>${esc(ANHS_CONFIG.version)}</strong></p><p>Ons Trop, Ons Trots</p><p>ANHS interventions, Head of Grade dashboards, discretionary approvals, flagged observations, annual points and three-month High Risk monitoring.</p><button class="secondary full" data-act="versions" aria-label="Open version history"><img class="brand-logo" src="jb-productions-logo-large.png" alt="JB Productions — version history"></button>${S.teacher?btn('Change my PIN','change-pin','','secondary'):''}`);}
async function render(){if(!S.teacher){login();return;}const r=S.route;if(r.page==='home')return home();if(r.page==='saved')return savedPage();if(r.page==='data-admin')return dataAdmin();if(r.page==='dashboard')return dashboard(r);if(['recent','all','unresolved','risk','learners','classes','learner'].includes(r.page))return listPage(r);if(r.page==='picker')return picker();if(r.page==='entry')return entryForm();if(r.page==='trends')return trends(r);if(r.page==='reports')return reports(r);if(r.page==='users')return users();if(r.page==='diagnostics')return diagnostics();home();}
document.addEventListener('click',async event=>{const el=event.target.closest('[data-act]');if(!el)return;const a=el.dataset.act,v=el.dataset.value,eventTicket=ticket();try{
 if(a==='refresh'){invalidateViews();S.forceOverview=true;const nav=++routeEpoch;eventTicket.nav=nav;const ref=await api('getAppData');if(!current(eventTicket))return;S.ref=ref;S.teacher=ref.teacher;await render();}if(a==='home')go({page:'home'});if(a==='back'){if(S.route.page==='home')return;history.back();}
 if(a==='teacher')go({page:'dashboard',scope:'teacher'});if(a==='register')go({page:'dashboard',scope:'register'});if(a==='hod')go({page:'dashboard',scope:'all'});
 if(a==='grade'){if(S.teacher.headOfGrade)go({page:'dashboard',scope:'grade',grade:S.teacher.headOfGrade});else if(allAccess())go({page:'dashboard',scope:'all'});else notify('Ask Admin to assign your grade.');}
 if(a==='view')viewRoute(v);if(a==='my-history')go({page:'all',scope:'teacher'});if(a==='learner')go({page:'learner',scope:'learner',learnerID:v});
 if(a==='record'){S.entryType=v;S.selected.clear();S.draft=null;S.requestID=uuid();go({page:'picker'});}
 if(a==='class'){$('#learner-search').value='';S.selectedClass=v;chooseLearners(S.ref.learners.filter(l=>l.className===v));}
 if(a==='choose'){if($('#multi').checked){S.selected.has(v)?S.selected.delete(v):S.selected.add(v);const q=$('#learner-search').value.toLowerCase();chooseLearners(S.ref.learners.filter(l=>q?(l.surname+' '+l.name+' '+l.id).toLowerCase().includes(q):l.className===S.selectedClass));}else{S.selected=new Set([v]);go({page:'entry'});}}
 if(a==='entry')go({page:'entry'});if(a==='quick'){$('#offence').value=v;offenceChanged();captureDraft({target:$('#offence')});}if(a==='other')$('#offence').focus();
 if(a==='remove')actionModal('incident',v,'remove');if(a==='approval')actionModal('incident',v,'approval');if(a==='resolve'){const [k,id]=v.split(':');actionModal(k,id,'resolve');}
 if(a==='close'){modalEpoch++;dialog.close();}if(a==='print'){if(S.route.page==='reports'&&!$('#report-output').textContent.trim()){notify('Generate the report first.');return;}window.print();}
 if(a==='generate')await generateReport();if(a==='more')await loadMore();if(a==='check-save')await checkSave();if(a==='saved-home'){S.draft=null;S.requestID='';go({page:'home'});}if(a==='data-admin')go({page:'data-admin'});if(a==='preview-import')await previewImport();if(a==='commit-import')await importCSV();if(a==='export-csv')await exportCSV();if(a==='users')go({page:'users'});if(a==='user-edit')editUser(v);if(a==='diagnostics')go({page:'diagnostics'});
 if(a==='about')about();if(a==='versions'){modalEpoch++;dialog.innerHTML=`<h2>Version History</h2><h3>v0.97b Alpha</h3><p>Cloudflare D1 backend; transactional totals; paginated history; saved-entry confirmation; resolution actions and explicit CSV imports.</p><h3>v0.97a-3 Alpha</h3><p>Latest-choice navigation, immediate menus, loading notes, dashboard prefetch and current-year dashboard payloads. Ons Trop, Ons Trots.</p><h3>v0.97a-2 Alpha</h3><p>Faster login, request-scoped sheet reads, grouped dashboard calculations, view reuse, request timings and a 30-second request limit.</p><h3>v0.97a-1 Alpha</h3><p>First ANHS package adapted from the JBP v0.97a starter.</p><ul><li>57 ANHS offences and four quick buttons</li><li>Head of Grade scope and intervention tracking</li><li>Approvals, removal reasons and audit history</li><li>Annual points, High Risk and flagged observations</li><li>Reports, trends and ANHS diagnostics</li></ul>${btn('Close','close')}`;}
 if(a==='change-pin'){modalEpoch++;dialog.innerHTML=`<h2>Change my PIN</h2><form id="request-pin-form"><label>Current PIN<input name="pin" type="password" inputmode="numeric" required></label><div class="form-error"></div><button>Continue</button></form>${btn('Close','close','','secondary')}`;}
 if(a==='logout'){const token=S.token,rememberToken=localStorage.getItem('anhs-remember')||'';localStorage.removeItem('anhs-remember');sessionStorage.removeItem('anhs-session');S.token='';modalEpoch++;dialog.close();login();api('logoutUser',{rememberToken},token).catch(()=>{});}
 if(a==='install'){if(window.installPrompt){await window.installPrompt.prompt();window.installPrompt=null;}else notify('Use your browser menu and choose Install app or Add to Home screen.');}
 }catch(e){if(current(eventTicket))showError(e);}});
document.addEventListener('input',e=>{captureDraft(e);if(e.target.id==='learner-search'){const q=e.target.value.toLowerCase();chooseLearners(q?S.ref.learners.filter(l=>(l.surname+' '+l.name+' '+l.id).toLowerCase().includes(q)):[]);}if(e.target.id==='history-search'){const q=e.target.value.toLowerCase();$('#history-results').innerHTML=historyTable(S.data.learners.filter(l=>(l.surname+' '+l.name+' '+l.id).toLowerCase().includes(q)));}});
document.addEventListener('change',e=>{captureDraft(e);if(e.target.id==='import-file'||e.target.id==='import-table'){S.importPlan=null;if($('#import-preview'))$('#import-preview').innerHTML='';}if(['from','to','range','report-type','report-class','report-learner'].includes(e.target.id))reportEpoch++;const id=e.target.id;if(id==='offence')offenceChanged();if(id==='grade-filter')go({...S.route,grade:e.target.value});if(id==='class-history')go({...S.route,className:e.target.value},true);if(id==='range')changeRange();if(['from','to'].includes(id)){if(S.route.page==='trends')drawTrends();else if($('#report-output'))$('#report-output').innerHTML='';}if(id==='multi'&&!e.target.checked){S.selected.clear();$('#selection-bar').innerHTML='';}if(['report-type','report-class','report-learner'].includes(id))$('#report-output').innerHTML='';});
document.addEventListener('submit',async e=>{
 e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f)),button=f.querySelector('button'),err=f.querySelector('.form-error');
 if(!button||f.dataset.busy==='yes')return;
 const t=ticket(),m=modalEpoch,isModal=['request-pin-form','action-form','user-form'].includes(f.id),auth=['login-form','pin-form'].includes(f.id),same=()=>current(t)&&(!isModal||m===modalEpoch);
 f.dataset.busy='yes';button.disabled=true;const label=button.textContent;button.textContent=auth?'Signing in…':'Saving…';if(err)err.textContent='';
 if(auth)startup('Signing in and loading school data…');
 try{
  if(f.id==='login-form'){S.remember=Boolean(d.remember);if(!S.remember)localStorage.removeItem('anhs-remember');const r=await api('loginUser',{email:d.username,pin:d.pin,rememberDevice:S.remember,includeAppData:true,requestID:uuid()});assertCurrent(t);await acceptLogin(r,t);}
  if(f.id==='pin-form'){const r=await api('changeOwnPin',{pinChangeToken:S.pinToken,newPin:d.pin,confirmPin:d.confirm,rememberDevice:S.remember,includeAppData:true,requestID:uuid()});assertCurrent(t);await acceptLogin(r,t);}
  if(f.id==='request-pin-form'){const r=await api('requestPinChange',{pin:d.pin});if(!same())return;S.pinToken=r.pinChangeToken;dialog.close();routeEpoch++;pinForm();}
  if(f.id==='entry-form'){
   if(!d.details.trim())throw Error('Details are required.');
   const receipt=await api(S.entryType==='incident'?'saveIncidents':'saveObservation',{learnerIDs:[...S.selected],code:d.code,type:d.type,date:d.date,period:d.period,details:d.details,recommended:d.recommended,confirmedTest:Boolean(d.confirmedTest),attention:Boolean(d.attention),requestID:S.requestID});
   if(t.session!==sessionEpoch)return;invalidateViews();if(same()){S.savedReceipt=receipt;S.draft=null;go({page:'saved'});}else notify('Your earlier submission was saved. Refresh this view to see changes.');
  }
  if(f.id==='action-form'){
   await api('recordAction',{kind:f.dataset.kind,id:f.dataset.id,action:f.dataset.action==='approval'?d.decision:f.dataset.action,reason:d.reason,comment:d.comment,points:d.points,resolutionAction:d.resolutionAction});
   if(t.session!==sessionEpoch)return;invalidateViews();if(same()){dialog.close();await render();if(current(t))notify('Decision saved.');}else notify('Your earlier decision was saved. Refresh this view to see changes.');
  }
  if(f.id==='user-form'){
   const savedUser=await api('saveAdminUser',{...d,teacherID:f.dataset.id,active:Boolean(d.active)});
   if(t.session!==sessionEpoch)return;invalidateViews();if(!same())return;
   if(savedUser.signInAgain){localStorage.removeItem('anhs-remember');sessionStorage.removeItem('anhs-session');S.token='';dialog.close();login();notify('Your changes were saved. Sign in again.');return;}const ref=await api('getAppData');if(!same())return;S.ref=ref;S.teacher=ref.teacher;dialog.close();await users();if(current(t))notify('User saved.');
  }
 }catch(e){if(!e.stale&&same()){if(err){err.textContent=e.message;if(f.id==='entry-form'){err.insertAdjacentHTML('beforeend',`<p>Keep these details. Check whether this submission saved before submitting again.</p>${btn('Check save status','check-save')}`);}}else showError(e);}else if(!e.stale&&t.session===sessionEpoch&&['entry-form','action-form','user-form'].includes(f.id)){notify('Earlier save: '+e.message);}}
 finally{if(auth&&t.session===sessionEpoch)endStartup();button.disabled=false;button.textContent=label;delete f.dataset.busy;}
});
dialog.addEventListener?.('cancel',()=>{modalEpoch++;});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();window.installPrompt=e;});
function captureDraft(e){if(e.target.closest?.('#entry-form'))S.draft=Object.fromEntries(new FormData($('#entry-form')));}
function restoreDraft(){if(!S.draft)return;const f=$('#entry-form');for(const [name,value] of Object.entries(S.draft)){const el=f.elements.namedItem(name);if(!el)continue;if(el.type==='checkbox')el.checked=Boolean(value);else el.value=value;}if(S.entryType==='incident'){offenceChanged();for(const name of ['recommended','confirmedTest']){const el=f.elements.namedItem(name);if(el&&S.draft[name]!==undefined){if(el.type==='checkbox')el.checked=true;else el.value=S.draft[name];}}}}
function savedPage(){const r=S.savedReceipt;if(!r?.found){go({page:'home'},true);return;}panel('Saved successfully',`<p class="prompt" role="status">Your ${r.entryType==='incident'?'incident':'observation'} ${r.records.length===1?'has':'entries have'} been saved.</p>${r.records.map(record=>{const l=r.learners.find(x=>x.id===record.LearnerID);return `<article class="card"><h2>${esc(record.LearnerName)}</h2><p>${esc(record.Class)} · Accession Number ${esc(record.LearnerID)}</p><strong>${esc(record.Offence||record.Type)}</strong><p>${esc(record.Details)}</p><p>${nice(record.DateOccurred)} · ${esc(record.Period)}</p><p>${r.entryType==='incident'?`${record.ApprovalStatus==='Pending'?'Awaiting approval · no points awarded yet':esc(record.Points)+' points'}${l?.points!=null?' · Current-year total: '+l.points:''}`:'Observation · no points'}</p><small>Saved ${esc(record.SubmittedAt)} · ${esc(record.RecordedName)}</small></article>`;}).join('')}<div class="bottom">${btn('Return to Home','saved-home')}</div>`);}
async function checkSave(){const t=ticket(),id=S.requestID,button=$('[data-act="check-save"]');if(button?.disabled)return;if(button)button.disabled=true;try{const r=await api('getSubmission',{requestID:id});if(!current(t)||id!==S.requestID)return;if(r.found){S.savedReceipt=r;S.draft=null;invalidateViews();go({page:'saved'});}else {const error=$('#entry-form .form-error');if(error)error.innerHTML=`<p>No saved record was found for this submission yet. Your details are still here. Check again before resubmitting if the original save is still running.</p>${btn('Check again','check-save')}`;}}finally{if(button)button.disabled=false;}}
async function loadMore(){const t=ticket(),base=S.data,offset=base.page?.nextOffset;if(offset==null)return;const button=$('[data-act="more"]');if(button?.disabled)return;if(button)button.disabled=true;try{const next=await fetchOverview({...S.route,offset});assertCurrent(t);const merged={...base,page:next.page};for(const key of ['incidents','observations','interventions'])merged[key]=[...new Map([...base[key],...next[key]].map(r=>[r.ID,r])).values()];merged.learners=base.learners.map(l=>({...l,interventions:merged.interventions.filter(i=>i.LearnerID===l.id&&String(i.Year)===today().slice(0,4))}));overviewCache.set(JSON.stringify(overviewArgs(S.route)),{data:merged,at:Date.now()});await render();}finally{if(button)button.disabled=false;}}
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(!quoted&&cell.length)throw Error('Unexpected quote in CSV field.');else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV has an unfinished quoted field.');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)throw Error('CSV needs headings and at least one data row.');const headers=rows.shift().map(x=>x.replace(/^\uFEFF/,'').trim());if(new Set(headers).size!==headers.length)throw Error('Duplicate CSV headings.');return rows.map((r,i)=>{if(r.length!==headers.length)throw Error('Wrong column count at CSV row '+(i+2));return Object.fromEntries(headers.map((h,n)=>[h,r[n]]));});}
function downloadText(filename,text,type='text/plain'){const link=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function dataAdmin(){if(S.teacher.role!=='Admin'){go({page:'home'},true);return;}S.importPlan=null;panel('Imports and exports',`<p>Import users or learners from CSV. Existing accession numbers and TeacherIDs are updated; new IDs are added. Rows left out of the file stay in the database. Set Status to Inactive to remove a learner from selection.</p><p>Keep accession numbers as text to preserve leading zeros. Editing the original spreadsheet does not update this app.</p><label>Import table<select id="import-table">${opt('Learners')}${opt('Users')}</select></label><label>CSV file<input id="import-file" type="file" accept=".csv,text/csv"></label><p>Learner headings: Accession Number, Surname, Name, Grade, Class, Status.</p><p>User headings: TeacherID, Name, Username, PIN, Role, RegisterClass, HeadOfGrade, Active. PIN may be blank for existing users; a new PIN forces a change at next login.</p>${btn('Validate and preview','preview-import')}<div id="import-preview"></div><hr><h2>Export CSV</h2><label>Table<select id="export-table">${['Users','Learners','Offences','Incidents','Observations','Interventions','Audit','TermCalendar'].map(x=>opt(x)).join('')}</select></label>${btn('Download CSV','export-csv','','secondary')}<p>Exported user PINs are blank. CSV exports are for review and data entry; use a D1 backup for complete disaster recovery.</p>`);}
async function previewImport(){const t=ticket(),file=$('#import-file').files[0],table=$('#import-table').value;if(!file)throw Error('Choose a CSV file.');const rows=parseCSV(await file.text());assertCurrent(t);const plan=await api('planImport',{table,rows});assertCurrent(t);S.importPlan={table,rows,plan};$('#import-preview').innerHTML=`<h2>Import preview</h2><p>${plan.total} rows · ${plan.added} added · ${plan.updated} updated</p><pre>${esc(JSON.stringify(plan.preview,null,2))}</pre><p>Review before importing. Each batch is committed together. A stopped import may contain earlier completed batches.</p>${btn('Import these rows','commit-import')}`;}
async function importCSV(){const t=ticket(),p=S.importPlan;if(!p)throw Error('Validate the CSV first.');if(S.importBusy)return;S.importBusy=true;const button=$('[data-act="commit-import"]');if(button)button.disabled=true;let complete=0;try{const check=await api('planImport',{table:p.table,rows:p.rows});assertCurrent(t);if(check.hash!==p.plan.hash)throw Error('Data changed since preview. Validate the file again.');const size=p.table==='Users'?10:100;for(let i=0;i<p.rows.length;i+=size){assertCurrent(t);const rows=p.rows.slice(i,i+size),plan=await api('planImport',{table:p.table,rows});assertCurrent(t);await api('commitImport',{table:p.table,rows,hash:plan.hash});complete+=rows.length;if(current(t))$('#import-preview').innerHTML=`<p>${complete} of ${p.rows.length} rows imported…</p>`;}if(!current(t))return;S.importPlan=null;invalidateViews();const ref=await api('getAppData');assertCurrent(t);S.ref=ref;S.teacher=ref.teacher;$('#import-preview').innerHTML=`<p class="prompt">Import completed: ${complete} rows.</p>`;}catch(e){if(current(t)){$('#import-preview').innerHTML=`<p>${complete} rows were confirmed imported. ${esc(e.message)} Review existing rows and validate again before continuing.</p>`;S.importPlan=null;}else if(t.session===sessionEpoch)notify('Import stopped after '+complete+' confirmed rows. Check the database before continuing.');}finally{S.importBusy=false;if(button)button.disabled=false;}}
async function exportCSV(){const t=ticket(),table=$('#export-table').value,rows=[];let offset=0;do{const r=await api('exportData',{table,offset});assertCurrent(t);rows.push(...r.rows);offset=r.nextOffset;}while(offset!=null);if(!rows.length){notify('No rows to export.');return;}const headers=Object.keys(rows[0]),quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const protect=x=>/^[=+@\-\t\r]/.test(String(x??''))?"'"+x:x;downloadText('ANHS_'+table+'_'+today()+'.csv','\uFEFF'+[headers,...rows.map(r=>headers.map(k=>protect(r[k])))].map(r=>r.map(quote).join(',')).join('\r\n'),'text/csv');}

async function boot(){history.replaceState({page:'home'},'','#home');const t=ticket();startup('Restoring your session and loading school data…');try{if(S.token){const ref=await api('getAppData');assertCurrent(t);checkVersion(ref);S.ref=ref;S.teacher=ref.teacher;$('#home').hidden=false;home();return;}const remembered=localStorage.getItem('anhs-remember');if(remembered){const r=await api('resumeRememberedLogin',{rememberToken:remembered,includeAppData:true});assertCurrent(t);if(r.success){await acceptLogin(r,t);return;}localStorage.removeItem('anhs-remember');}}catch(e){if(!current(t))return;S.token='';sessionStorage.removeItem('anhs-session');notify(e.message);}finally{if(t.session===sessionEpoch)endStartup();}if(current(t))login();}
if('serviceWorker' in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
boot();
